class Team{
  githubName:string
  name:string
  jobTitle:string
  introduce:string

  constructor(githubName:string, name:string, jobTitle:string, introduce:string) {
    this.githubName = githubName
    this.name = name
    this.jobTitle = jobTitle
    this.introduce = introduce
  }
}

export const teams:Map<string,Team[]> = new Map([
  [
    '现在的',
    [
      {
        githubName:'Cxl-Xc',
        name:'Cxl-Xc',
        jobTitle:'社长',
        introduce:'未知'
      },
      {
        avatar:'xinqiyi1024',
        jobTitle:'不知',
        name:'xinqiyi1024',
        introduce:'未知'
      },
      {
        avatar:'dai147444612',
        name:'dai147444612',
        jobTitle:'副社长',
        introduce:'未知'
      },
      {
        avatar:'011011100',
        name:'011011100',
        jobTitle:'不知',
        introduce:'未知'
      },
      {
        avatar:'13336778832',
        name:'13336778832',
        jobTitle:'不知',
        introduce:'未知'
      },
      {
        avatar:'wxcdico',
        name:'wxcdico',
        jobTitle:'不知',
        introduce:'未知'
      },
      {
        avatar:'namelesslight',
        name:'namelesslight',
        jobTitle:'不知',
        introduce:'未知'
      },
      {
        avatar:'Zhengke0509',
        name:'Zhengke0509',
        jobTitle:'不知',
        introduce:'未知'
      },
    ]
  ],
  [
    '2019年',
    [
      {
        avatar:'woshixiaotugo',
        name:'woshixiaotugo',
        jobTitle:'社长',
        introduce:'未知'
      },
      {
        avatar:'sakurazro',
        name:'sakurazro',
        jobTitle:'副社长',
        introduce:'未知'
      },
      {
        avatar:'xiaoxunyao',
        name:'xiaoxunyao',
        jobTitle:'副社长',
        introduce:'全职开源的码农'
      },
      {
        avatar:'wuaqing',
        name:'wuaqing',
        jobTitle:'财务',
        introduce:'未知'
      },
      {
        avatar:'qiuqiuya-get',
        name:'qiuqiuya-get',
        jobTitle:'学习部',
        introduce:'未知'
      },
      {
        avatar:'missyou-zxt',
        name:'missyou-zxt',
        jobTitle:'维修部',
        introduce:'未知'
      },
      {
        avatar:'FanHoozy',
        name:'FanHoozy',
        jobTitle:'学习部',
        introduce:'未知'
      },
    ]
  ]
])
